### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by jiangzhongshi** [jovyan/pythreejs#149]
This is a great library but I am having a weird issue. I can install the library (the master branch ) locally in my MacOS with node (v9.3.0) and npm (5.6.0), but within my Docker (Ubuntu 16.04, node v9.3.0, npm v5.5.1 ), it gives the following error message. 
I am not familiar with `nodejs`, so I hope someone may be able to interpret the message and tells me what I am doing wrong. Thanks!

```
Installing collected packages: pythreejs
  Running setup.py develop for pythreejs
    Complete output from command /opt/conda/envs/py35/bin/python -c "import setuptools, tokenize;__file__='/opt/pythreejs/setup.py';f=ge
tattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --n
o-deps:
    setup.py entered
    $PATH=/opt/conda/envs/py35/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/us
r/bin:/sbin:/bin
    running develop
    running js
    > npm run build:all

    > jupyter-threejs@1.0.0-beta.3 build:all /opt/pythreejs/js
    > npm run build:labextension


    > jupyter-threejs@1.0.0-beta.3 build:labextension /opt/pythreejs/js
    > rimraf lab-dist && mkdirp lab-dist && cd lab-dist && npm pack ..

    npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
    npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
    npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
    npm WARN lifecycle jupyter-threejs@1.0.0-beta.3~prepublish: cannot run in wd %s %s (wd=%s) jupyter-threejs@1.0.0-beta.3 npm run auto
gen && npm run build:bundles /opt/pythreejs/js
    jupyter-threejs-1.0.0-beta.3.tgz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/pythreejs/setup.py", line 108, in <module>
        setup(**setup_args)
      File "/opt/conda/envs/py35/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/envs/py35/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/conda/envs/py35/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/pythreejs/setupbase.py", line 469, in run
        [self.run_command(cmd) for cmd in cmds]
      File "/opt/pythreejs/setupbase.py", line 469, in <listcomp>
        [self.run_command(cmd) for cmd in cmds]
      File "/opt/conda/envs/py35/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/envs/py35/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/pythreejs/setupbase.py", line 265, in run
        c.run()
      File "/opt/pythreejs/setupbase.py", line 390, in run
        raise ValueError(('missing files: %s' % missing))
    ValueError: missing files: ['pythreejs/static/extension.js', 'pythreejs/static/index.js', 'js/src/core/BufferAttribute.autogen.js',
'pythreejs/core/BufferAttribute_autogen.py', 'docs/source/_static/jupyter-threejs.js', 'docs/source/_static/three.js']

    ----------------------------------------
Command "/opt/conda/envs/py35/bin/python -c "import setuptools, tokenize;__file__='/opt/pythreejs/setup.py';f=getattr(tokenize, 'open',
open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with erro
r code 1 in /opt/pythreejs/
```

**Comment by vidartf** [comment]
Thanks for the report, to help ease the troubleshooting, I'd appreciate it if you could supply some extra information:

1. Does installing the latest packed beta work for you (`pip install --pre pythreejs`)? Or is it only install from master that fails?
2. What is the command(s) you used to install pythreejs from master?
3. What is your version of npm/node?

**Comment by jiangzhongshi** [comment]
Thanks for the followup, I was using (Ubuntu 16.04, node v9.3.0, npm v5.5.1 ) inside a Docker. Installing directly from the master branch. The command was `pip install -e .`

It should be a specific issue as I was able to install it elsewhere.

**Comment by vidartf** [comment]
I'm curious about this line:
```
npm WARN lifecycle jupyter-threejs@1.0.0-beta.3~prepublish: cannot run in wd %s %s (wd=%s) jupyter-threejs@1.0.0-beta.3 npm run auto gen && npm run build:bundles /opt/pythreejs/js
```

Are there any access restrictions on `/opt/pythreejs/js`? The build generates some files, so it will need write permission. If that's not it, I'm not sure if I can figure out anything more from the logs. Then I would recommend you try to run the npm commands manually (in the `js` folder):

 - `npm install`
 - `npm run build:all`

And if those work, re-attempt `pip install -v -e .` (notice the `-v` verbose flag).

**Comment by jiangzhongshi** [comment]
Thanks for the response, here is the output dump.
```
root@5bbb0881c9e4:/opt/pythreejs/js# npm install

> uglifyjs-webpack-plugin@0.4.6 postinstall /opt/pythreejs/js/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm WARN lifecycle jupyter-threejs@1.0.0-beta.3~prepublish: cannot run in wd %s %s (wd=%s) jupyter-threejs@1.0.0-beta.3 npm run autogen && npm run build:bundles /opt/pythreejs/js
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 128 packages and updated 1 package in 5.86s
```
```
root@5bbb0881c9e4:/opt/pythreejs/js# npm run build:all

> jupyter-threejs@1.0.0-beta.3 build:all /opt/pythreejs/js
> npm run build:labextension


> jupyter-threejs@1.0.0-beta.3 build:labextension /opt/pythreejs/js
> rimraf lab-dist && mkdirp lab-dist && cd lab-dist && npm pack ..

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm WARN lifecycle jupyter-threejs@1.0.0-beta.3~prepublish: cannot run in wd %s %s (wd=%s) jupyter-threejs@1.0.0-beta.3 npm run autogen && npm run build:bundles /opt/pythreejs/js
jupyter-threejs-1.0.0-beta.3.tgz
```
```
root@5bbb0881c9e4:/opt/pythreejs# pip install -v -e .
Obtaining file:///opt/pythreejs
  Running setup.py (path:/opt/pythreejs/setup.py) egg_info for package from file:///opt/pythreejs
    Running command python setup.py egg_info
    setup.py entered
    $PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    running egg_info
    writing pythreejs.egg-info/PKG-INFO
    writing dependency_links to pythreejs.egg-info/dependency_links.txt
    writing requirements to pythreejs.egg-info/requires.txt
    writing top-level names to pythreejs.egg-info/top_level.txt
    package init file 'pythreejs/__init__.py' not found (or not a regular file)
    reading manifest file 'pythreejs.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.*' under directory 'pythreejs/static'
    warning: no previously-included files found matching 'docs/#*'
    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/dist'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '.git' found anywhere in distribution
    warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
    warning: no files found matching '*.json' under directory 'pythreejs/renderers/shaders'
    writing manifest file 'pythreejs.egg-info/SOURCES.txt'
  Source in /opt/pythreejs has version 1.0.0b3, which satisfies requirement pythreejs==1.0.0b3 from file:///opt/pythreejs
Requirement already satisfied: ipywidgets<8,>=7 in /opt/conda/lib/python3.6/site-packages (from pythreejs==1.0.0b3)
Requirement already satisfied: ipydatawidgets>=1.1.1 in /opt/conda/lib/python3.6/site-packages (from pythreejs==1.0.0b3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.6/site-packages (from pythreejs==1.0.0b3)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.6/site-packages (from ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: traitlets>=4.3.1 in /opt/conda/lib/python3.6/site-packages (from ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: nbformat>=4.2.0 in /opt/conda/lib/python3.6/site-packages (from ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: widgetsnbextension~=3.0.0 in /opt/conda/lib/python3.6/site-packages (from ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: ipython>=4.0.0 in /opt/conda/lib/python3.6/site-packages (from ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: ipyscales>=0.1.1 in /opt/conda/lib/python3.6/site-packages (from ipydatawidgets>=1.1.1->pythreejs==1.0.0b3)
Requirement already satisfied: six in /opt/conda/lib/python3.6/site-packages (from ipydatawidgets>=1.1.1->pythreejs==1.0.0b3)
Requirement already satisfied: jupyter_client in /opt/conda/lib/python3.6/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: tornado>=4.0 in /opt/conda/lib/python3.6/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: ipython_genutils in /opt/conda/lib/python3.6/site-packages (from traitlets>=4.3.1->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: decorator in /opt/conda/lib/python3.6/site-packages (from traitlets>=4.3.1->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.6/site-packages (from nbformat>=4.2.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: jupyter_core in /opt/conda/lib/python3.6/site-packages (from nbformat>=4.2.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: notebook>=4.4.1 in /opt/conda/lib/python3.6/site-packages (from widgetsnbextension~=3.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.6/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: jedi>=0.10 in /opt/conda/lib/python3.6/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.6/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: simplegeneric>0.8 in /opt/conda/lib/python3.6/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: prompt_toolkit<2.0.0,>=1.0.4 in /opt/conda/lib/python3.6/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: pygments in /opt/conda/lib/python3.6/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: pexpect in /opt/conda/lib/python3.6/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: pyzmq>=13 in /opt/conda/lib/python3.6/site-packages (from jupyter_client->ipykernel>=4.5.1->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: python-dateutil>=2.1 in /opt/conda/lib/python3.6/site-packages (from jupyter_client->ipykernel>=4.5.1->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: parso==0.1.* in /opt/conda/lib/python3.6/site-packages (from jedi>=0.10->ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.6/site-packages (from prompt_toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipywidgets<8,>=7->pythreejs==1.0.0b3)
Installing collected packages: pythreejs
  Running setup.py develop for pythreejs
    Running command /opt/conda/bin/python -c "import setuptools, tokenize;__file__='/opt/pythreejs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    setup.py entered
    $PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    running develop
    running js
    > npm run build:all

    > jupyter-threejs@1.0.0-beta.3 build:all /opt/pythreejs/js
    > npm run build:labextension


    > jupyter-threejs@1.0.0-beta.3 build:labextension /opt/pythreejs/js
    > rimraf lab-dist && mkdirp lab-dist && cd lab-dist && npm pack ..

    npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
    npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
    npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
    npm WARN lifecycle jupyter-threejs@1.0.0-beta.3~prepublish: cannot run in wd %s %s (wd=%s) jupyter-threejs@1.0.0-beta.3 npm run autogen && npm run build:bundles /opt/pythreejs/js
    jupyter-threejs-1.0.0-beta.3.tgz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/pythreejs/setup.py", line 108, in <module>
        setup(**setup_args)
      File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/pythreejs/setupbase.py", line 469, in run
        [self.run_command(cmd) for cmd in cmds]
      File "/opt/pythreejs/setupbase.py", line 469, in <listcomp>
        [self.run_command(cmd) for cmd in cmds]
      File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/pythreejs/setupbase.py", line 265, in run
        c.run()
      File "/opt/pythreejs/setupbase.py", line 390, in run
        raise ValueError(('missing files: %s' % missing))
    ValueError: missing files: ['pythreejs/static/extension.js', 'pythreejs/static/index.js', 'js/src/core/BufferAttribute.autogen.js', 'pythreejs/core/BufferAttribute_autogen.py', 'docs/source/_static/jupyter-threejs.js', 'docs/source/_static/three.js']
Cleaning up...
Command "/opt/conda/bin/python -c "import setuptools, tokenize;__file__='/opt/pythreejs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/pythreejs/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "/opt/conda/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/opt/conda/bin/python -c "import setuptools, tokenize;__file__='/opt/pythreejs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/pythreejs/
```

**Comment by vidartf** [comment]
Hmm. Again I see `npm WARN lifecycle jupyter-threejs@1.0.0-beta.3~prepublish: cannot run in wd %s %s (wd=%s) jupyter-threejs@1.0.0-beta.3 npm run autogen && npm run build:bundles /opt/pythreejs/js` in the `npm install` output. Are you sure that /opt/pythreejs/js is writable by the install process?

**Comment by jiangzhongshi** [comment]
Hi, thanks for the catch. Although the folder is writable, I think the problem is related to this message.

And then I searched for wd problem and find this https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

I used the 
```
root@5bbb0881c9e4:/opt/pythreejs/js# npm install --unsafe-perm
root@5bbb0881c9e4:/opt/pythreejs/js# npm run build:all --unsafe-perm
```
then `root@5bbb0881c9e4:/opt/pythreejs/# pip install -v -e .`

And it works.

Thanks!

**Comment by vidartf** [comment]
Good that you solved the issue. Just a note of caution though: While this solved the issue, I would normally be sceptical to using root and flags with "unsafe" in the name. This might be indicative of a deeper permissions issue, as was the case of the stackoverflow question you linked.
