### ISSUE TITLE
Unable to install on jupyter via anaconda

### ISSUE THREAD

**Issue by rolyhudson** [jovyan/pythreejs#240]
Looking forward to using threejs in a notebook environment but using
`conda install -c conda-forge pythreejs`
I get the error:
`ImportError: DLL load failed: The specified module could not be found.`
Something related to the cython module?

I have anaconda 1.9.2 with jupyter 5.6.0

Here is the full log when I try:
```
C:\Users\Admin>conda install -c conda-forge pythreejs
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Admin\Anaconda3

  added / updated specs:
    - pythreejs


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2018.11.29 |       ha4d7672_0         179 KB  conda-forge
    certifi-2018.11.29         |        py37_1000         144 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         323 KB

The following NEW packages will be INSTALLED:

    ipydatawidgets:  4.0.0-py_0            conda-forge
    ipyscales:       0.3.0-py_0            conda-forge
    pythreejs:       2.0.2-py37_1000       conda-forge

The following packages will be UPDATED:

    ca-certificates: 2018.10.15-ha4d7672_0 conda-forge --> 2018.11.29-ha4d7672_0 conda-forge
    certifi:         2018.10.15-py37_1000  conda-forge --> 2018.11.29-py37_1000  conda-forge

Proceed ([y]/n)? y
Downloading and Extracting Packages
ca-certificates-2018 | 179 KB    | ############################################################################ | 100%
certifi-2018.11.29   | 144 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: - Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pythreejs\__init__.py", line 8, in <module>
    from .pythreejs import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pythreejs\pythreejs.py", line 14, in <module>
    from ipywidgets import Widget, widget_serialization
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 15, in <module>
    from ipykernel.comm import Comm
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    import zmq
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::pythreejs-2.0.2-py37_1000'.
LinkError: post-link script failed for package conda-forge::pythreejs-2.0.2-py37_1000
running your command again with `-v` will provide additional information
location of failed script: C:\Users\Admin\Anaconda3\Scripts\.pythreejs-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pythreejs\__init__.py", line 8, in <module>
    from .pythreejs import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pythreejs\pythreejs.py", line 14, in <module>
    from ipywidgets import Widget, widget_serialization
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 15, in <module>
    from ipykernel.comm import Comm
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    import zmq
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.


Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::pythreejs-2.0.2-py37_1000
running your command again with `-v` will provide additional information
location of failed script: C:\Users\Admin\Anaconda3\Scripts\.pythreejs-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pythreejs\__init__.py", line 8, in <module>
    from .pythreejs import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pythreejs\pythreejs.py", line 14, in <module>
    from ipywidgets import Widget, widget_serialization
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 15, in <module>
    from ipykernel.comm import Comm
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    import zmq
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by SylvainCorlay** [comment]
Hello, could you please report the output of `conda list`?

**Comment by rolyhudson** [comment]
Yes that works. Many Thanks
