### ISSUE TITLE
Can not use in JupyterLite

### ISSUE THREAD

**Issue by sunzhuo** [jovyan/pythreejs#402]
I runned folowing cells in [JupyterLite](https://jupyterlite.github.io/demo/lab/index.html):

```python 
%pip install pythreejs
```

```python
from pythreejs import *
from IPython.display import display
from math import pi
# Reduce repo churn for examples with embedded state:
from pythreejs._example_helper import use_example_model_ids
use_example_model_ids()
BoxGeometry(
    width=5,
    height=10,
    depth=15,
    widthSegments=5,
    heightSegments=10,
    depthSegments=15)
```

And get these error messages:

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'PreviewModel' from module 'jupyter-threejs'
Error: No version of module jupyter-threejs is registered
    at f.loadClass (https://jupyterlite.github.io/demo/extensions/@jupyter-widgets/jupyterlab-manager/static/134.402424ef4079078b2e0e.js?v=402424ef4079078b2e0e:1:74855)
    at f.loadModelClass (https://jupyterlite.github.io/demo/extensions/@jupyter-widgets/jupyterlab-manager/static/150.1a6d6a3a0542a41bec5a.js?v=1a6d6a3a0542a41bec5a:1:10729)
    at f._make_model (https://jupyterlite.github.io/demo/extensions/@jupyter-widgets/jupyterlab-manager/static/150.1a6d6a3a0542a41bec5a.js?v=1a6d6a3a0542a41bec5a:1:7517)
    at f.new_model (https://jupyterlite.github.io/demo/extensions/@jupyter-widgets/jupyterlab-manager/static/150.1a6d6a3a0542a41bec5a.js?v=1a6d6a3a0542a41bec5a:1:5137)
    at f.handle_comm_open (https://jupyterlite.github.io/demo/extensions/@jupyter-widgets/jupyterlab-manager/static/150.1a6d6a3a0542a41bec5a.js?v=1a6d6a3a0542a41bec5a:1:3894)
    at _handleCommOpen (https://jupyterlite.github.io/demo/extensions/@jupyter-widgets/jupyterlab-manager/static/134.402424ef4079078b2e0e.js?v=402424ef4079078b2e0e:1:73392)
    at v._handleCommOpen (https://jupyterlite.github.io/demo/build/6591.94ed352.js:1:28742)
    at async v._handleMessage (https://jupyterlite.github.io/demo/build/6591.94ed352.js:1:30636)
```

**Comment by merlinND** [comment]
Hello @sunzhuo,
This sounds like the same issue as #389.

**Comment by Homomorpheus** [comment]
In Jupyterlite, this problem can stem from too few packages being present in the python environment at build time.
Try changing your requirements.txt to the requirements.txt of this project: https://github.com/triadtitans/rigid_body_interactive
