### ISSUE TITLE
jupyter nbextension install --py --symlink --sys-prefix pythreejs

### ISSUE THREAD

**Issue by katierose1029** [jovyan/pythreejs#76]
I am trying to install a development installation and am running into this error:
    (To be honest I think it is because I'm using python3 but I didn't want to assume)

Traceback (most recent call last):
  File "/Users/KaitlynChait/anaconda3/envs/py35/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/Users/KaitlynChait/anaconda3/envs/py35/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/KaitlynChait/anaconda3/envs/py35/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/KaitlynChait/anaconda3/envs/py35/lib/python3.5/site-packages/notebook/nbextensions.py", line 969, in start
    super(NBExtensionApp, self).start()
  File "/Users/KaitlynChait/anaconda3/envs/py35/lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/KaitlynChait/anaconda3/envs/py35/lib/python3.5/site-packages/notebook/nbextensions.py", line 745, in start
    self.install_extensions()
  File "/Users/KaitlynChait/anaconda3/envs/py35/lib/python3.5/site-packages/notebook/nbextensions.py", line 724, in install_extensions
    **kwargs
  File "/Users/KaitlynChait/anaconda3/envs/py35/lib/python3.5/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Users/KaitlynChait/anaconda3/envs/py35/lib/python3.5/site-packages/notebook/nbextensions.py", line 1143, in _get_nbextension_metadata
    'it is missing the `_jupyter_nbextension_paths()` method.'.format(module))
KeyError: 'The Python module pythreejs is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'

**Comment by katierose1029** [comment]
however this line works for some reason:
jupyter nbextension install pythreejs

but enable does not

**Comment by SylvainCorlay** [comment]
Python 3 should not be an issue. 

Could you provide the versions of notebook and ipywidgets that are installed?

```
conda list | grep  notebook
``` 

Just to be sure, I assume that you followed the instructions of the README?

```
$ git clone https://github.com/jovyan/pythreejs.git
$ cd pythreejs
$ pip install -e .
$ jupyter nbextension install --py --symlink --sys-prefix pythreejs
$ jupyter nbextension enable --py --sys-prefix pythreejs
```

**Comment by katierose1029** [comment]
notebook                  4.3.2                     <pip> 

I recently updated my version of notebook within the week so I don't think it could be this? 

I did follow the instructions.

**Comment by SylvainCorlay** [comment]
@katierose1029 did you end up finding a solution?

**Comment by katierose1029** [comment]
@SylvainCorlay I'm not sure if I want to call it a solution but I reinstalled anaconda on my computer from scratch and created a new environment. 
I think something was most definitely broken in my kernel.

**Comment by SylvainCorlay** [comment]
Ok. Sorry I could not help more.
